#docker run -d --env=NEO4J_AUTH=none --publish=7474:7474 --publish=7687:7687   --volume=$HOME/neo4j/data:/data     neo4j
version: "3.7"
services:
  app:
    image: jorgementx/movies2neo4j:v2
    links:
      - neo4j
    depends_on:
      - neo4j

  neo4j:
    image: neo4j
    restart: always
    environment:
      NEO4J_AUTH: none
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ~/neo4j/data:/data


#networks:
#  default:
#    external:
#      name: eureka
