apiVersion: v1
kind: Service
metadata:
  name: neo4j-service
spec:
  type: ClusterIP
  selector:
    app: database
  ports:
  - port: 7474
    targetPort: 7474
    name: http
  - port: 7687
    targetPort: 7687
    name: bolt
