apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: neo4j
        image: neo4j
        env:
            - name: NEO4J_AUTH
              value: neo4j-service
        ports:
        - containerPort: 7474
          name: http
        - containerPort: 7687
          name: bolt 
        volumeMounts:
          - name: neo4j-volume
            mountPath: /data
      volumes:
        - name: neo4j-volume
          persistentVolumeClaim:
            claimName: neo4j-claim
